version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: dvwa-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: dvwa
      MYSQL_DATABASE: dvwa
      MYSQL_USER: dvwa
      MYSQL_PASSWORD: dvwa
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dvwa-net

  dvwa:
    image: vulnerables/web-dvwa:latest
    container_name: dvwa-app
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "5000:80"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=dvwa
      - MYSQL_DB=dvwa
      - MYSQL_ROOT_PASSWORD=dvwa
    networks:
      - dvwa-net
    volumes:
      - dvwa_data:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: dvwa-phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - dvwa-net

volumes:
  db_data:
  dvwa_data:

networks:
  dvwa-net:
    driver: bridge
